#!/usr/bin/env bash
#Set the input field separator to ':'

IFS=":"



# Read the /etc/passwd file line by line

while read -r username password uid gid user_info home_dir shell; do

	  # Extract additional information about the user

	    group_name=$(getent group "$gid" | cut -d: -f1)

	      command_shell=$(basename "$shell")



	        # Print the user details

		  echo "The user $username is part of the $group_name gang, lives in $home_dir, and rides $command_shell."

		    echo "User ID's place is protected by the passcode $password, more info about the user here: $user_info"

		      echo

	      done < "/etc/passwd"











#while IFS=':' read -r username _ uid _ _ home _; do

#  echo "Username: $username"

#    echo "User ID: $uid"

 #     echo "Home Directory: $home"

#done < /etc/passwd


