#!/usr/bin/env bash 
#blah blah blah
#!/bin/bash



# Set IFS to colon (:) to separate fields in /etc/passwd

IFS=":"



# Read /etc/passwd line by line

while read -r username password uid gid user_info home shell; do

	    # Extract additional user information from /etc/passwd

	        group_name=$(getent group "$gid" | cut -d: -f1)

		    command_shell=$(basename "$shell")



		        # Display user information

			    echo "The user $username is part of the $group_name gang, lives in $home and rides $command_shell."

			        echo "User ID's place is protected by the passcode $password, more info about the user here: $user_info"

				    echo

			    done < /etc/passwd


