#!/usr/bin/env bash 
#!/bin/bash



# Set the input field separator to ':' to parse /etc/passwd

IFS=":"



# Read the file /etc/passwd line by line

while read -r username password uid gid user_info home shell; do

	    # Extract the group name from /etc/group using the group ID

	        group_name=$(grep ":$gid:" /etc/group | cut -d: -f1)



		    # Extract the password from user_info

		        password=$(echo "$user_info" | cut -d',' -f1)



			    # Extract additional user ID info

			        id_info=$(echo "$user_info" | cut -d',' -f2-)



				    # Display user information

				        echo "The user $username is part of the $group_name gang, lives in $home and rides $shell."

					    echo "User ID's place is protected by the passcode $password, more info about the user here: $id_info"

					        echo

					done < /etc/passwd
