#!/usr/bin/env bash
#log_file="access.log"

log_file="access.log"



awk '{ print $1,$9 }' "$log_file" | sort | uniq -c | awk '{ printf "%-10s %-10s %-10s\n", $2, $3, $1 }'





#awk '{ print $1, $9 }' | uniq -c | sort -nr | head -n 10 
