#!/usr/bin/env bash
#3. If 9, say Hi!
n=1                                                                                                                                                                       
while [ $n -le 10 ]
do                                                                                                                                                                       
        echo "Best School"                                                                                                                                                
        (( n++ ))
if [ $n = 10 ]
then
	echo "Hi"
fi	
done
