#!/usr/bin/env bash 
#Write a Bash script that loops from 1 to 10 and:
n=1
while [ $n -le 10 ]
do 
	(( n++ ))
if [ $n = 5 ]
then 
	echo "bad luck"
elif [ $n = 9 ]
then 
	echo "good luck"
else
	echo "Best School"
fi
done 
