#!/usr/bin/env bash
# Sperstitious numbers
n=1
while [ $n -le 20 ]
do
	echo "$n"
	(( n++ ))
case $n in
	5) echo "bad luck from China";;
	10) echo "bad luck from Japan";;
	18) echo "bad luck from Italy";;
esac
done
