#!/usr/bin/env bash
#making a clock
x=0
while ((x<13))
do
	echo "Hour: $x"
	y=1
	((x=x+1))
	while ((y<60))
	do
		echo "$y"
		((y=y+1))
	done
done









#h=0
#while [ $h -le 12 ]
#do echo "hour: $h"
#	m=1
#	while [ $m -le 59 ]
#	do echo "$m"
#	m=$(( $m+1 ))
#	done 
#h=$(( $h+1 ))
#done
