#!/usr/bin/env bash
#Making a clock
h=0
while [ $h -le 12 ]
do echo "hour: $h"
	m=1
	while [ $m -le 59 ] 
	do 
		echo "$m"
		m=$(( $m+1 ))
	done
	h=$(( $h+1 ))
done







#while [ $m -eq 59 ]
#do echo "hour: $h"
#	if [ $h -le 12 ]
#	then echo "$m"
#		m=$(( $m+1 ))
#		h=$(( $h+1 ))
#	fi
#done





#while echo "hour: $h"
#do if [ $m -eq 59 ]
#then echo "$m"
#	m=$(( $m+1 ))
#fi
#h=$(( $h+1 ))
#done





#while [ $h -le 12 ]
#do
#echo "hour: $h"
#	#h=$(( $h+1 ))
#	while [ $m -le 59 ]
#	do
#		echo "$m"
		#m=$(( $m+1 ))
#	done
#done
