#!/usr/bin/env bash
#For ls
for file in *
do
	if [[ "$file" != .* ]] && [[ "$file" == *-* ]]; then
		name=$(echo "$file" | cut -d'-' -f2-)
		echo "$name"
	fi
done







#for file in *; do 
#	if [[ $file != .* && $file == -* ]]; then
#		filename="${file#*-}"
#		echo "$filename"
#	fi 
#done
