#!/usr/bin/env bash
#do you really know?

#!/bin/bash



file="school.txt"



if [[ -e $file ]]; then

	  echo "school file exists"

	    if [[ -s $file ]]; then

		        echo "school file is not empty"

			    if [[ -f $file ]]; then

				          echo "school is a regular file"

					      fi

					        else

							    echo "school file is empty"

							      fi

						      else

							        echo "school file does not exist"

fi














file_path="school.txt"
if [ -e "$file_path" ]; then
	echo "school file exists"
if [ -s "$file_path" ]; then
	echo "school file is not empty"
else 
	echo "school file is empty"
fi
if [ -f "$file_path" ]; then
	echo "school is a regular file"
fi
else 
	echo "school file does not exist"
fi
