#!/usr/bin/env bash
#Get the list of all processes and their details
ps -auxf










#processes=$(ps -eo pid,ppid,user,cmd --forest)

# Display the processes in a user-oriented format
#echo "PID  PPID  USER       CMD"
#echo "------------------------"
#echo "$processes"
