#!/usr/bin/env bash
# Display header

echo "PID     PPID    USER       COMMAND"



# Retrieve process information and format it

ps -ef --forest --no-headers | awk '{printf "%-8s%-8s%-10s%s\n", $2, $3, $1, $8}'


