#!/usr/bin/env bash
# Get the list of all processes and their details
processes=$(ps -eo pid,ppid,user,cmd --forest)

# Display the processes in a user-oriented format
echo "PID  PPID  USER       CMD"
echo "------------------------"
echo "$processes"











# Display header

#echo "PID     PPID    USER       COMMAND"



# Retrieve process information and format it

#ps -ef --forest --no-headers | awk '{printf "%-8s%-8s%-10s%s\n", $2, $3, $1, $8}'


