#!/usr/bin/env bash
#test test

pid_file="/var/run/myscript.pid"



# Function to handle SIGTERM signal

function handle_sigterm() {

    echo "I hate the kill command"

}



# Function to handle SIGINT signal

function handle_sigint() {

    echo "Y U no love me?!"

}



# Function to handle SIGQUIT and SIGTERM signals

function handle_sigquit() {

    rm "$pid_file"

    exit

}



# Create the PID file

echo "$$" > "$pid_file"



# Register signal handlers

trap 'handle_sigterm' SIGTERM

trap 'handle_sigint' SIGINT

trap 'handle_sigquit' SIGQUIT SIGTERM



# Display message indefinitely

while true; do

    echo "To infinity and beyond"

    sleep 1

done


