#!/usr/bin/env bash
#test test
PID_FILE="/var/run/my_process.pid"



start() {

    if [ -f "$PID_FILE" ]; then

        echo "manage_my_process is already started."

        return

    fi



    ./manage_my_process &

    echo $! > "$PID_FILE"

    echo "manage_my_process started."

}



stop() {

    if [ ! -f "$PID_FILE" ]; then

        echo "manage_my_process is not running."

        return

    fi



    pid=$(cat "$PID_FILE")

    kill "$pid"

    rm "$PID_FILE"

    echo "manage_my_process stopped."

}



restart() {

    stop

    start

    echo "manage_my_process restarted."

}



case "$1" in

    start)

        start

        ;;

    stop)

        stop

        ;;

    restart)

        restart

        ;;

    *)

        echo "Usage: $0 {start|stop|restart}"

        ;;

esac


