#!/usr/bin/env bash
# Search for processes with the name containing "bash" using pgrep

pgrep -l 



#pids=$(pgrep bash)



# Iterate over each PID and retrieve the process name

#for pid in $pids; do

  # Retrieve the process name using the /proc filesystem

# process_name=$(grep -Po '^Name:\s+\K.*' "/proc/$pid/status")



  # Display the PID and process name

# echo "PID: $pid, Process Name: $process_name"

#done


