#!/usr/bin/env bash
# Find the process ID (PID)

pkill -f 4-to_infinity_and_beyond









#pid=$(pgrep -f "4-to_infinity_and_beyond")



#if [ -z "$pid" ]; then

#  echo "Process '4-to_infinity_and_beyond' not found."

#else

  # Terminate the process

 # pkill -P "$pid"

  #echo "Process '4-to_infinity_and_beyond' (PID: $pid) stopped."

#fi


